# NOTE:
# Dependabot won't follow `labels: []`.
# https://github.com/dependabot/dependabot-core/issues/11783

version: 2

# TODO:
# Add support for bumping version of `packageManager` specified inside `package.json`.
# https://github.com/dependabot/dependabot-core/issues/4830
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    labels: ['build']
    commit-message:
      prefix: 'build'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    labels: ['ci']
    commit-message:
      prefix: 'ci'
      include: 'scope'
