[match]
dot = true

[pull_request]
check_title = true

[schedule]
tasks = ["node_audit"]

[push_tag]
formatters = ["prettier"]
linters = ["check_dist", "eslint", "ast_grep"]

[options.linters]
yamllint = ["--strict"]

[formatters]
prettier = ["**/*.yml", "**/*.ts", "**/*.md", "**/*.json"]
taplo = ["**/*.toml"]

[linters]
node_audit = ["package.json", "pnpm-lock.yaml"]
check_dist = ["src/**/*.ts", "package.json", "pnpm-lock.yaml"]
typos = ["**/*", "!dist/**"]
yamllint = ["**/*.yml"]
actionlint = [".github/workflows/*.yml"]
eslint = ["**/*.ts"]
ast_grep = ["**/*.ts"]
alex = ["**/*.md"]
markdownlint_cli2 = ["**/*.md"]
vale = ["**/*.md"]
taplo = ["**/*.toml"]
