[match]
dot = true

[pull_request]
check_title = true

[push_tag]
formatters = ['prettier']
linters = ['eslint', 'ast_grep']

[options.linters]
check_dist = ['build']
yamllint = ['--strict']

[formatters]
prettier = ['**/*.yml', '**/*.ts', '**/*.md', '**/*.json']
taplo = ['**/*.toml']

[linters]
check_dist = ['src/**/*.ts', 'pnpm-lock.yaml']
typos = ['**/*', '!dist/**']
yamllint = ['**/*.yml']
actionlint = ['.github/workflows/*.yml']
eslint = ['**/*.ts']
ast_grep = ['**/*.ts']
alex = ['**/*.md']
markdownlint_cli2 = ['**/*.md']
vale = ['**/*.md']
taplo = ['**/*.toml']
