[match]
dot = true

[schedule]
linters = ["node-audit"]

[push]
formatters = ["prettier"]
linters = ["tsc", "check-dist", "eslint", "ast-grep"]

[formatters]
prettier = ["**/*.yml", "**/*.ts", "**/*.md", "**/*.json"]
tombi = ["**/*.toml"]

[linters]
node-audit = ["package.json", "pnpm-lock.yaml"]
tsc = ["**/*.ts", "package.json", "pnpm-lock.yaml"]
check-dist = ["src/**/*.ts", "package.json", "pnpm-lock.yaml"]
typos = ["**/*", "!dist/**"]
yamllint = ["**/*.yml"]
actionlint = [".github/workflows/*.yml"]
eslint = ["**/*.ts"]
ast-grep = ["**/*.ts"]
alex = ["**/*.md"]
markdownlint-cli2 = ["**/*.md"]
vale = ["**/*.md"]
tombi = ["**/*.toml"]

[args.linters]
yamllint = ["--strict"]
tombi = ["--error-on-warnings"]
eslint = ["--max-warnings", "0"]