name: 'PR Insight'
description: 'GitHub Action for checking pull requests'
author: 'Shigure Kurosaki'
inputs:
  config-path:
    description: 'The path to the Insight config file.'
    default: '.github/insight.toml'
  event-name:
    description: 'The name of the event that triggered the workflow run.'
    default: ${{ github.event_name }}
  ref-type:
    description: 'The type of ref that triggered the workflow run.'
    default: ${{ github.ref_type }}
  pull-request-type:
    description: 'The type of pull request event.'
    default: ${{ github.event.action }}
  pull-request-title:
    description: 'The title of pull request event.'
    default: ${{ github.event.pull_request.title }}
  token:
    description: 'Personal access token (PAT) used to fetch the repository.'
    default: ${{ github.token }}
  repository:
    description: 'Repository name with owner.'
    default: ${{ github.repository }}
  pull-request-number:
    description: 'The number of the pull request to check.'
    default: ${{ github.event.pull_request.number }}
outputs:
  any-changed:
    description: 'Returns `true` if any of the configured patterns matched.'
runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  color: 'black'
  icon: 'check-square'
