# TODO: https://github.com/cli/cli/issues/5193

name: CD

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+', 'v[0-9]+.[0-9]+.[0-9]+-canary.[0-9]+']

permissions:
  contents: read

jobs:
  archive-assets:
    name: Archive assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Packaging assets
        run: |
          base_name="insight-$GITHUB_REF_NAME"

          tar czf "$base_name.tar.gz" --transform "s,^,$base_name/," -- dist/ LICENSE README.md action.yml
      - name: Uploading assets
        uses: actions/upload-artifact@v6
        with:
          name: assets
          path: insight-${{ github.ref_name }}.tar.gz

  create-attestation:
    permissions:
      id-token: write
      attestations: write
    needs: archive-assets
    runs-on: ubuntu-latest
    name: Create attestation
    steps:
      - name: Downloading assets
        uses: actions/download-artifact@v7
        with:
          name: assets
      - name: Generate attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: insight-${{ github.ref_name }}.tar.gz

  create-release-note:
    permissions:
      contents: write
    needs: archive-assets
    runs-on: ubuntu-latest
    name: Create release note
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Downloading assets
        uses: actions/download-artifact@v7
        with:
          name: assets
      - name: Generate release note
        # NOTE:
        # The recommended workflow for publishing an immutable release
        # will be to initially create the release as a draft,
        # attach any associated assets, and then publish the draft.
        # https://github.com/orgs/community/discussions/171210#discussioncomment-14237940
        run: |
          if [[ $GITHUB_REF_NAME = *canary* ]]; then
            npx changelogithub@latest --prerelease --draft
          else
            npx changelogithub@latest --draft
          fi

          gh release upload "$GITHUB_REF_NAME" "insight-$GITHUB_REF_NAME.tar.gz"
          gh release edit "$GITHUB_REF_NAME" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
