# TODO: Automatically publish the GitHub Action to the Marketplace.
# https://github.com/cli/cli/issues/5193

name: CD

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+', 'v[0-9]+.[0-9]+.[0-9]+-canary.[0-9]+']

permissions:
  contents: read

env:
  ARTIFACT_NAME: insight-${{ github.ref_name }}.tar.gz

jobs:
  archive-assets:
    name: Archive assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Package assets
        run: tar czf "$ARTIFACT_NAME" --transform "s,^,insight-$GITHUB_REF_NAME/," -- dist/ LICENSE README.md action.yml
      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          archive: false
          path: ${{ env.ARTIFACT_NAME }}

  create-attestation:
    permissions:
      id-token: write
      attestations: write
      # artifact-metadata: write
      # https://github.com/actions/attest/blob/main/README.md#container-image
    needs: archive-assets
    runs-on: ubuntu-latest
    name: Create attestation
    steps:
      - name: Download artifact
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Generate attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: ${{ env.ARTIFACT_NAME }}

  create-release-note:
    permissions:
      contents: write
    needs: archive-assets
    runs-on: ubuntu-latest
    name: Create release note
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Enable pnpm
        run: corepack enable pnpm
      - name: Download artifact
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Generate release note
        # NOTE: The recommended workflow for publishing an immutable release
        # will be to initially create the release as a draft,
        # attach any associated assets, and then publish the draft.
        # https://github.com/orgs/community/discussions/171210#discussioncomment-14237940
        run: |
          if [[ $GITHUB_REF_NAME == *canary* ]]; then
            pnpm dlx changelogithub --prerelease --draft
          else
            pnpm dlx changelogithub --draft
          fi

          gh release upload "$GITHUB_REF_NAME" "$ARTIFACT_NAME"
          gh release edit "$GITHUB_REF_NAME" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
