name: Check Pull Request Title

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  insight:
    name: Insight
    if: ${{ github.event.action == 'opened' || github.event.changes.title != null }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run Insight
        uses: ./
        with:
          check-pull-request-title: true
