name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  insight:
    name: Insight
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Run Insight
        id: insight
        uses: ./
  test:
    name: Test
    needs: insight
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.steps.insight.outputs.any_changed }}
